# Overview: build and create a release via Google Cloud Deploy for GKE
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable
# Update these values, if desired
substitutions:
  _REPO_NAME: maven-demo-app
  _APP_NAME: demo-app
  _PIPELINE_NAME: security-demo-pipeline
steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args:
    - -c
    - |
      lc=`git rev-parse HEAD`
      echo "lc is $lc"
      slci="git rev-parse HEAD'^'"
      slc=`echo $slci | bash`
      echo "slc is $slc"

      #      export fname=$(git diff --name-only HEAD\^)
      #echo "fname is $fname"
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/private-pool'
