# Overview: build and create a release via Google Cloud Deploy for GKE
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable
# Update these values, if desired
substitutions:
  _REPO_NAME: maven-demo-app
  _APP_NAME: demo-app
  _PIPELINE_NAME: security-demo-pipeline
steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args:
    - -c
    - |
      git fetch --unshallow
      lc=`git rev-parse HEAD`
      echo "lc is $lc"
      slc="git rev-parse HEAD'^'"
      echo "slc is $slc"
      fname=`git show --format="" --name-only`
      echo "fname is $fname"
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/private-pool'
