# Overview: build and create a release via Google Cloud Deploy for GKE
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable
# Update these values, if desired
substitutions:
  _REPO_NAME: maven-demo-app
  _APP_NAME: demo-app
  _PIPELINE_NAME: security-demo-pipeline
steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args:
    - -c
    - |
      lc=`git log -n 1 --pretty=format:"%H"`
      slc=`git log -n 1 --skip 1 --pretty=format:"%H"`
      export fname=`git diff --name-status [$lc [$slc]]`
      echo "fname is $fname"
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/private-pool'
