apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
        env:
          - name: PORT
            value: "8080"
          - name: TARGET
            value: "Production Env - K8s Cluster"              
